name: oneMail
description: A new Flutter project.

publish_to: "none"

version: 1.0.3+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  enough_mail:
    git:
      url: https://github.com/Enough-Software/enough_mail.git
  enough_mail_html: 
    git:
      url: https://github.com/Enough-Software/enough_mail_html.git
  enough_media: 
    git:
      url: https://github.com/Enough-Software/enough_media.git
  enough_html_editor: 
    git:
      url: https://github.com/Enough-Software/enough_html_editor.git
  cupertino_icons: ^1.0.2
  mailer: ^5.0.2
  url_launcher: ^6.0.18
  file_picker: ^4.2.0
  intl:
  modal_bottom_sheet: ^2.0.0
  permission_handler: ^8.3.0
  fluttertoast: ^8.0.0
  get: ^4.3.8
  flutter_web_auth: ^0.4.0
  flutter_vector_icons: ^1.0.0
  path_provider: ^2.0.2
  shared_preferences: ^2.0.8
  cached_network_image: ^3.1.0+1
  iconly: ^1.0.1
  awesome_notifications: ^0.6.21
  quick_actions: ^0.6.0+9
  photo_view: ^0.13.0
  open_file: ^3.2.1
  firebase_crashlytics: ^2.4.3
  flutter_inappwebview: ^5.3.2
  google_fonts: ^2.2.0
  splashscreen: ^1.3.5
  flutter_admob_app_open: ^1.1.1
  flutter_rating_bar: ^4.0.0
  in_app_review: ^2.0.3
  thumbnailer: ^2.0.0
  share: ^2.0.4
  image_picker: ^0.8.4+4
  firebase_messaging: ^11.2.4
  dio: ^4.0.4
  flutter_svg: ^1.0.0
  device_info_plus: ^3.2.1
  flutter_web_browser: ^0.16.0
  f_logs: ^2.0.0
  flutter_contacts: ^1.1.2
  get_it: ^7.2.0
  workmanager: ^0.4.1
  firebase_remote_config: ^2.0.0
  expandable: ^5.0.1
  firebase_remote_config_web: ^1.0.5
  carousel_slider: ^4.0.0
  

dependency_overrides:
  url_launcher: ^6.0.6
  photo_view: ^0.13.0
  google_mobile_ads: ^1.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/helpAndSupport/
